# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160811_1118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
